# Generated by Django 3.2.5 on 2021-07-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='weight',
            field=models.FloatField(),
        ),
    ]
